CREATE DATABASE ALISBOOK_BD
GO

USE ALISBOOK_BD
GO

CREATE TABLE ROL (
    IDROL INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(100),
    FECHAREGISTRO DATETIME)
GO

CREATE TABLE PERMISO (
    IDPERMISO INT PRIMARY KEY,
    NOMBREMENU NVARCHAR(100),
    FECHAREGISTRO DATETIME,
    IDROL INT FOREIGN KEY REFERENCES ROL(IDROL))
GO

CREATE TABLE USUARIO (
    IDUSUARIO INT PRIMARY KEY,
    DOCUMENTO NVARCHAR(20),
    NOMBRECOMPLETO NVARCHAR(100),
    CORREO NVARCHAR(100),
    CLAVE NVARCHAR(100),
    ESTADO NVARCHAR(60),
    FECHAREGISTRO DATETIME,
    IDROL INT FOREIGN KEY REFERENCES ROL(IDROL))
GO

CREATE TABLE FORMAS_PAGO (
    IDFORMAPAGO INT PRIMARY KEY,
    TIPOPAGO NVARCHAR(50))
GO

CREATE TABLE PROVEEDOR (
    IDPROVEEDOR INT PRIMARY KEY,
    DOCUMENTO NVARCHAR(20),
    RAZONSOCIAL NVARCHAR(100),
    CORREO NVARCHAR(100),
    TELEFONO NVARCHAR(20),
    ESTADO NVARCHAR(60),
    FECHAREGISTRO DATETIME)
GO

CREATE TABLE COMPRA (
    IDCOMPRA INT PRIMARY KEY,
    TIPODOCUMENTO NVARCHAR(50),
    NUMERODOCUMENTO NVARCHAR(50),
    MONTOTOTAL DECIMAL(10,2),
    FECHAREGISTRO DATETIME,
    IDUSUARIO INT FOREIGN KEY REFERENCES USUARIO(IDUSUARIO),
    IDPROVEEDOR INT FOREIGN KEY REFERENCES PROVEEDOR(IDPROVEEDOR),
    IDFORMAPAGO INT FOREIGN KEY REFERENCES FORMAS_PAGO(IDFORMAPAGO))
GO

CREATE TABLE CATEGORIA (
    IDCATEGORIA INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(100),
    ESTADO NVARCHAR(60),
    FECHAREGISTRO DATETIME)
GO

CREATE TABLE PRODUCTO (
    IDPRODUCTO INT PRIMARY KEY,
    CODIGO NVARCHAR(50),
    NOMBRE NVARCHAR(100),
    DESCRIPCION NVARCHAR(255),
    STOCK INT,
    PRECIOCOMPRA DECIMAL(10,2),
    PRECIOVENTA DECIMAL(10,2),
    ESTADO NVARCHAR(60),
    FECHAREGISTRO DATETIME,
    IDCATEGORIA INT FOREIGN KEY REFERENCES CATEGORIA(IDCATEGORIA))
GO

CREATE TABLE DETALLECOMPRA (
    IDDETALLECOMPRA INT PRIMARY KEY,
    PRECIOVENTA DECIMAL(10,2),
    PRECIOCOMPRA DECIMAL(10,2),
    CANTIDAD INT,
    MONTOTOTAL DECIMAL(10,2),
    FECHAREGISTRO DATETIME,
    IDCOMPRA INT FOREIGN KEY REFERENCES COMPRA(IDCOMPRA),
    IDPRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO(IDPRODUCTO))
GO

CREATE TABLE VENTA (
    IDVENTA INT PRIMARY KEY,
    TIPODOCUMENTO NVARCHAR(50),
    NUMERODOCUMENTO NVARCHAR(50),
    DOCUMENTOCLIENTE NVARCHAR(20),
    NOMBRECLIENTE NVARCHAR(100),
    MONTOPAGO DECIMAL(10,2),
    MONTOCAMBIO DECIMAL(10,2),
    MONTOTOTAL DECIMAL(10,2),
    FECHAREGISTRO DATETIME,
    IDUSUARIO INT FOREIGN KEY REFERENCES USUARIO(IDUSUARIO))
GO

CREATE TABLE DETALLEVENTA (
    IDDETALLEVENTA INT PRIMARY KEY,
    PRECIOVENTA DECIMAL(10,2),
    CANTIDAD INT,
    SUBTOTAL DECIMAL(10,2),
    FECHAREGISTRO DATETIME,
    IDVENTA INT FOREIGN KEY REFERENCES VENTA(IDVENTA),
    IDPRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO(IDPRODUCTO))
GO

CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY,
    DOCUMENTO NVARCHAR(20),
    NOMBRECOMPLETO NVARCHAR(100),
    CORREO NVARCHAR(100),
    TELEFONO NVARCHAR(20),
    ESTADO NVARCHAR(60),
    FECHAREGISTRO DATETIME)
GO
