CREATE DATABASE ALISBOOK_BD
GO

USE ALISBOOK_BD
GO

CREATE TABLE ROLES (
    IDROL INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(100),
    FECHAREGISTRO DATETIME)
GO

CREATE TABLE PERMISOS (
    IDPERMISO INT PRIMARY KEY,
    NOMBREMENU NVARCHAR(100),
    FECHAREGISTRO DATETIME,
    IDROL INT FOREIGN KEY REFERENCES ROLES(IDROL))
GO

CREATE TABLE USUARIOS (
    IDUSUARIO INT PRIMARY KEY,
    DOCUMENTO NVARCHAR(20),
    NOMBRECOMPLETO NVARCHAR(100),
    CORREO NVARCHAR(100),
    CLAVE NVARCHAR(100),
    ESTADO NVARCHAR(60),
    FECHAREGISTRO DATETIME,
    IDROL INT FOREIGN KEY REFERENCES ROLES(IDROL))
GO

CREATE TABLE FORMAS_PAGO (
    IDFORMAPAGO INT PRIMARY KEY,
    TIPOPAGO NVARCHAR(50))
GO

CREATE TABLE PROVEEDORES (
    IDPROVEEDOR INT PRIMARY KEY,
    DOCUMENTO NVARCHAR(20),
    RAZONSOCIAL NVARCHAR(100),
    CORREO NVARCHAR(100),
    TELEFONO NVARCHAR(20),
    ESTADO NVARCHAR(60),
    FECHAREGISTRO DATETIME)
GO

CREATE TABLE COMPRAS (
    IDCOMPRA INT PRIMARY KEY,
    TIPODOCUMENTO NVARCHAR(50),
    NUMERODOCUMENTO NVARCHAR(50),
    MONTOTOTAL DECIMAL(10,2),
    FECHAREGISTRO DATETIME,
    IDUSUARIO INT FOREIGN KEY REFERENCES USUARIOS(IDUSUARIO),
    IDPROVEEDOR INT FOREIGN KEY REFERENCES PROVEEDORES(IDPROVEEDOR),
    IDFORMAPAGO INT FOREIGN KEY REFERENCES FORMAS_PAGO(IDFORMAPAGO))
GO

CREATE TABLE CATEGORIAS (
    IDCATEGORIA INT PRIMARY KEY,
    DESCRIPCION NVARCHAR(100),
    ESTADO NVARCHAR(60),
    FECHAREGISTRO DATETIME)
GO

CREATE TABLE PRODUCTOS (
    IDPRODUCTO INT PRIMARY KEY,
    CODIGO NVARCHAR(50),
    NOMBRE NVARCHAR(100),
    DESCRIPCION NVARCHAR(255),
    STOCK INT,
    PRECIOCOMPRA DECIMAL(10,2),
    PRECIOVENTA DECIMAL(10,2),
    ESTADO NVARCHAR(60),
    FECHAREGISTRO DATETIME,
    IDCATEGORIA INT FOREIGN KEY REFERENCES CATEGORIAS(IDCATEGORIA))
GO

CREATE TABLE DETALLECOMPRAS (
    IDDETALLECOMPRA INT PRIMARY KEY,
    PRECIOVENTA DECIMAL(10,2),
    PRECIOCOMPRA DECIMAL(10,2),
    CANTIDAD INT,
    MONTOTOTAL DECIMAL(10,2),
    FECHAREGISTRO DATETIME,
    IDCOMPRA INT FOREIGN KEY REFERENCES COMPRAS(IDCOMPRA),
    IDPRODUCTO INT FOREIGN KEY REFERENCES PRODUCTOS(IDPRODUCTO))
GO

CREATE TABLE VENTAS (
    IDVENTA INT PRIMARY KEY,
    TIPODOCUMENTO NVARCHAR(50),
    NUMERODOCUMENTO NVARCHAR(50),
    DOCUMENTOCLIENTE NVARCHAR(20),
    NOMBRECLIENTE NVARCHAR(100),
    MONTOPAGO DECIMAL(10,2),
    MONTOCAMBIO DECIMAL(10,2),
    MONTOTOTAL DECIMAL(10,2),
    FECHAREGISTRO DATETIME,
    IDUSUARIO INT FOREIGN KEY REFERENCES USUARIOS(IDUSUARIO))
GO

CREATE TABLE DETALLEVENTAS (
    IDDETALLEVENTA INT PRIMARY KEY,
    PRECIOVENTA DECIMAL(10,2),
    CANTIDAD INT,
    SUBTOTAL DECIMAL(10,2),
    FECHAREGISTRO DATETIME,
    IDVENTA INT FOREIGN KEY REFERENCES VENTAS(IDVENTA),
    IDPRODUCTO INT FOREIGN KEY REFERENCES PRODUCTOS(IDPRODUCTO))
GO

CREATE TABLE CLIENTES (
    IDCLIENTE INT PRIMARY KEY,
    DOCUMENTO NVARCHAR(20),
    NOMBRECOMPLETO NVARCHAR(100),
    CORREO NVARCHAR(100),
    TELEFONO NVARCHAR(20),
    ESTADO NVARCHAR(60),
    FECHAREGISTRO DATETIME)
GO
